export function renderLoginFeature(deps) {
  const { seed, state, tenant, escapeHTML, button, icon } = deps;
  const tenants = seed.tenants || [];
  const authDraft = state.authDraft || {};
  const defaultUserByRole = state.authRole === 'TEACHER' ? 'teacher@iams.school.edu' : state.authRole === 'STUDENT' ? 'student@iams.school.edu' : 'management@iams.school.edu';
  const workspaceHint = authDraft.workspace || state.authSession?.tenant?.slug || 'iams';
  const userHint = authDraft.userId || defaultUserByRole;
  const passwordHint = authDraft.password || 'IAMS@123';
  const authMode = state.authMode || 'signin';

  const socialButtons = `<div class="social-row"><button type="button" class="social-btn google" data-action="social-auth" data-provider="Google" aria-label="Continue with Google"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#EA4335" d="M12 10.2v3.9h5.5c-.2 1.3-1.6 3.9-5.5 3.9-3.3 0-6-2.7-6-6s2.7-6 6-6c1.9 0 3.2.8 3.9 1.5l2.7-2.6C17.1 3.4 14.8 2.5 12 2.5a9.5 9.5 0 1 0 0 19c5.5 0 9.2-3.9 9.2-9.3 0-.6-.1-1.1-.2-1.6H12z"/></svg><span>Google</span></button><button type="button" class="social-btn facebook" data-action="social-auth" data-provider="Facebook" aria-label="Continue with Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#1877F2" d="M24 12a12 12 0 1 0-13.9 11.9v-8.4H7.1V12h3V9.4c0-3 1.8-4.7 4.5-4.7 1.3 0 2.7.2 2.7.2v3h-1.5c-1.5 0-2 .9-2 1.9V12h3.4l-.5 3.5h-2.9v8.4A12 12 0 0 0 24 12z"/></svg><span>Facebook</span></button><button type="button" class="social-btn apple" data-action="social-auth" data-provider="Apple" aria-label="Continue with Apple"><svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#111111" d="M16.7 12.7c0-2.2 1.8-3.2 1.9-3.2-1-1.5-2.6-1.7-3.2-1.8-1.4-.1-2.7.8-3.4.8-.7 0-1.8-.8-3-.8-1.6 0-3 .9-3.8 2.3-1.6 2.8-.4 6.9 1.2 9.2.8 1.1 1.7 2.3 3 2.3 1.2 0 1.6-.7 3.1-.7s1.9.7 3.1.7c1.3 0 2.1-1.1 2.9-2.3.9-1.3 1.3-2.5 1.3-2.6 0 0-2.6-1-2.6-3.9zM14.6 6.3c.7-.8 1.1-1.8 1-2.8-1 .1-2.1.6-2.8 1.4-.6.7-1.1 1.8-1 2.8 1 .1 2.1-.5 2.8-1.4z"/></svg><span>Apple</span></button></div>`;

  const authModeSwitch = `<div class="auth-mode-switch" role="tablist" aria-label="Authentication mode">
      <button type="button" class="auth-mode-btn ${authMode === 'signin' ? 'active' : ''}" data-action="set-auth-mode" data-mode="signin">Sign In</button>
      <button type="button" class="auth-mode-btn ${authMode === 'signup' ? 'active' : ''}" data-action="set-auth-mode" data-mode="signup">Sign Up</button>
    </div>`;

  const signInForm = `<form class="auth-card" id="login-form"><div class="auth-card-header"><p class="eyebrow">Welcome back</p><h2>Welcome to NotebookXL</h2><p>Sign in to continue to your school workspace.</p></div>${authModeSwitch}<div class="auth-steps"><span class="active">1. School Workspace</span><span class="active">2. Role</span><span class="active">3. Sign in</span></div><label>School ID or Workspace<input name="workspace" id="workspace-input" autocomplete="organization" placeholder="iams" value="${escapeHTML(workspaceHint)}" list="workspace-options" /></label><datalist id="workspace-options"><option value="iams">IAMS (ISRAR AHMED MISSION SCHOOL)</option>${tenants.map((school) => `<option value="${escapeHTML(school.slug || '')}">${escapeHTML(school.school?.name || school.name || 'School')}</option>`).join('')}</datalist><p class="workspace-domain">${escapeHTML(workspaceHint)}.notebookxl.com</p><input type="hidden" name="tenantId" value="${escapeHTML(state.tenantId || '')}" /><div class="role-picker" aria-label="Choose access role"><span>I am a</span><div>${['SCHOOL_ADMIN','TEACHER','STUDENT'].map((role) => `<button type="button" class="role-option ${state.authRole === role ? 'selected' : ''}" data-action="set-auth-role" data-role="${role}">${role === 'SCHOOL_ADMIN' ? 'Management' : role[0] + role.slice(1).toLowerCase()}</button>`).join('')}</div></div><label>Email ID<input name="userId" id="login-user" type="email" autocomplete="username" placeholder="Enter registered email" value="${escapeHTML(userHint)}" required /></label><label>Password<input name="password" type="password" autocomplete="current-password" placeholder="Enter password" value="${escapeHTML(passwordHint)}" required /></label><label class="remember-row"><input type="checkbox" name="remember" /> Remember me</label><button class="btn btn-primary btn-full" type="submit">Sign In ${icon('arrow')}</button><div class="auth-divider"><span>or sign in with</span></div>${socialButtons}<div class="auth-divider"><span>⚡ 1-Click IAMS School Access</span></div><div class="social-row"><button type="button" class="social-btn" data-action="use-default-user" data-role="SCHOOL_ADMIN" data-workspace="iams" data-user="management@iams.school.edu" data-password="IAMS@123">Management</button><button type="button" class="social-btn" data-action="use-default-user" data-role="TEACHER" data-workspace="iams" data-user="teacher@iams.school.edu" data-password="IAMS@123">Teacher</button><button type="button" class="social-btn" data-action="use-default-user" data-role="STUDENT" data-workspace="iams" data-user="student@iams.school.edu" data-password="IAMS@123">Student</button></div><button type="button" class="forgot" data-action="forgot-password">Forgot password?</button><p class="auth-help">Active School: <b>IAMS (ISRAR AHMED MISSION SCHOOL)</b></p></form>`;

  const signUpForm = `<form class="auth-card" id="signup-form"><div class="auth-card-header"><p class="eyebrow">Create your account</p><h2>Start with NotebookXL</h2><p>Use email signup or continue with Google, Facebook, or Apple.</p></div>${authModeSwitch}<label>Full Name<input name="name" autocomplete="name" placeholder="Enter your full name" required /></label><label>School / Institution<input name="school" autocomplete="organization" placeholder="Enter school name" value="${escapeHTML(workspaceHint)}" required /></label><label>Email ID<input type="email" name="email" autocomplete="email" placeholder="Enter your email" value="${escapeHTML(userHint)}" required /></label><label>Mobile Number<input name="mobile" autocomplete="tel" placeholder="Enter mobile number" required /></label><label>Password<input type="password" name="password" autocomplete="new-password" placeholder="Create password" required /></label><label>Confirm Password<input type="password" name="confirmPassword" autocomplete="new-password" placeholder="Confirm password" required /></label><button class="btn btn-primary btn-full" type="submit">Create Account ${icon('arrow')}</button><div class="auth-divider"><span>or continue with</span></div>${socialButtons}<p class="auth-help">Already have an account? <button type="button" class="auth-inline-link" data-action="set-auth-mode" data-mode="signin">Sign In</button></p></form>`;

  const resetForm = `<form class="auth-card" id="reset-password-form"><div class="auth-card-header"><p class="eyebrow">Account recovery</p><h2>Reset your password</h2><p>Enter your email and set a new password to continue.</p></div><label>Email ID<input type="email" name="email" autocomplete="email" placeholder="Enter registered email" required /></label><label>New Password<input type="password" name="newPassword" autocomplete="new-password" placeholder="Enter new password" required /></label><label>Confirm New Password<input type="password" name="confirmPassword" autocomplete="new-password" placeholder="Re-enter new password" required /></label><button class="btn btn-primary btn-full" type="submit">Reset Password ${icon('arrow')}</button><p class="auth-help">Remembered your password? <button type="button" class="auth-inline-link" data-action="set-auth-mode" data-mode="signin">Back to Sign In</button></p></form>`;

  const activeForm = authMode === 'signup' ? signUpForm : authMode === 'reset' ? resetForm : signInForm;

  return `<main class="auth-page modern-auth"><button class="auth-back" data-action="go-landing">← Back to NotebookXL</button><section class="auth-layout"><aside class="auth-intro auth-split-left"><a class="brand brand-light" data-action="go-landing"><span class="brand-mark">N</span>NOTEBOOK<span>XL</span></a><div><p class="eyebrow">One intelligent workspace for your entire school.</p><h1>Your school. One intelligent workspace.</h1><p>Students, teachers, academics and school insights — connected in one place.</p></div><div class="auth-mini-metrics"><article><small>Attendance</small><b>94.6%</b></article><article><small>Teacher Attendance</small><b>97.1%</b></article><article><small>School Pulse</small><b>Live</b></article><article><small>Erum AI</small><b>Enabled</b></article></div></aside><div class="auth-card-wrap auth-split-right">${activeForm}</div></section></main>`;
}
